name: Build PiTrezor Image

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Настройка глобального правила для обхода блокировки git:// протокола
    - name: Configure Git to use HTTPS instead of GIT protocol
      run: |
        git config --global url."https://".insteadOf git://

    # Шаг 2: Скачивание репозитория вместе со всеми зависимостями
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # Шаг 3: Исправление устаревших репозиториев Debian Buster в Dockerfile автора
    - name: Fix EOL Debian Buster repositories in Dockerfile
      run: |
                sed -i '/FROM debian:buster/a RUN echo "deb http://archive.debian.org/debian buster main\\ndeb http://archive.debian.org/debian-security buster/updates main" > /etc/apt/sources.list' Dockerfile

        

    # Шаг 3: Очистка диска (Yocto требует много места)
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    # Шаг 4: Запуск компиляции в Docker (с правами sudo)
    - name: Run Build Script in Docker
      run: |
        chmod +x build-pitrezor.sh
        sudo ./build-pitrezor.sh master raspberrypi0-wifi


    # Шаг 5: Сохранение готового образа
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pitrezor-rpi0-image
        path: imgs/*.zip
