name: Build PiTrezor Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Fix git protocol (https instead of git://)
        run: |
          git config --global url."https://git.yoctoproject.org/".insteadOf "git://git.yoctoproject.org/"
          git config --global url."https://github.com/".insteadOf "git://github.com/"
          git config --global url."https://git.openembedded.org/".insteadOf "git://git.openembedded.org/"

      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Debug Show repo structure
        run: |
          echo "=== ROOT CONTENTS ==="
          ls -la
          echo ""
          echo "=== LOOKING FOR POKY BUILD META ==="
          find . -maxdepth 2 -type d -name "*poky*" -o -name "*build*" -o -name "*meta*"

      - name: Install Yocto dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gawk wget git diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-p
